### ISSUE TITLE
nodes?

### ISSUE THREAD

**Issue by matslats** [amitaibu/og#108]
I'm curious as to the reasoning behind a group continuing to be a node type. To me it seems like a natural candidate to be its own contentEntity.
- it is a bit confusing for developers and site builders to deal with group content and groups as content at the same time.
- groups have little need for revisions, sticky, promote, and would probably prefer to define their own properties
- if groups were a contentEntityType, then there could be fieldable groupTypes which might be more natural for developers and site-builders than membership types
- as an EntityType, group would benefit from having its own handlers for access, lists, viewBuilders
  Overall much greater flexibility and less confusion.
  Am I wrong? Perhaps this project values architectural continuity over the Drupal Way?

**Comment by amitaibu** [comment]
It _can_ be a node, the same way it could be any other `ContentEntity`.

Here's an answer I have in another thread:
1. OG7 is already not node-centric, every fieldable entity can be a group/ group content
1. Adding an entity reference already in OG7 is what connects a group content to a group
Groups are more often then not real content. They need to be published/ unpublished, comments, shown along other content, etc'
1. Groups can be private (with OG access module), so {node_access} gives us all that
1. On top of that I think that migrating all the OG7 nodes to a new entity wouldn't be nice for the site builders/ devs that already use it.

**Comment by damiankloip** [comment]
As far as I know there is not a restriction on what entity type and bundle
can be a group. In theory this can still be any entity type you like. Where
has the assumption come from? The current access code maybe?

As far as a new entity type goes, this has come up (many times) before and
this has draw backs. You are then limited to one entity type for groups,
but also you would have to make sure the group entities worked and looked
as expected on a site, potentially creating more work. Whereas, taking node
as an example, they are likely already used and look as expected. If it was
another entity type you might be doing additional work to make them look
like nodes on your site.

**Comment by matslats** [comment]
Thanks for your answers I shall be experimenting with making my own
entityType! Could be valuable testing. Might be willing to submit code
suggestions. I'm good enough at git on drupal.org. been doing d8 full
time for 2 years now. Matthew

On Thu, Dec 24, 2015, at 12:21 AM, Amitai Burstein wrote:

> It _can_ be a node, the same way it could be any other ContentEntity.
> 
> Here's an answer I have in another thread:
> 1. OG7 is already not node-centric, every fieldable entity can be a
>    group/ group content
> 2. Adding an entity reference already in OG7 is what connects a group
>    content to a group
> 
> Groups are more often then not real content. They need to be published/
> unpublished, comments, shown along other content, etc'
> 1. Groups can be private (with OG access module), so {node_access} gives
>    us all that
> 2. On top of that I think that migrating all the OG7 nodes to a
>    new entity wouldn't be nice for the site builders/ devs that
>    already use it.
> 
> — Reply to this email directly or view it on GitHub[1].

Links:
1. https://github.com/amitaibu/og/issues/108#issuecomment-166892233

**Comment by damiankloip** [comment]
D8 full time huh? Have you been contributing back to core then? I put a lot
of time into D8!

**Comment by matslats** [comment]
Only a few bug reports, not patches. I've been working alone on another
major project. http://drupal.org/project/mutual_credit Waiting nearly a
year for OG then I just found the gizra github was abandoned and it was
happening here!

Find out more about my work in local money systems Twitter: @matslats
Personal web site[1] including my blog, Adventures in mutual credit[2]
Brief bio and articles on shareable.net[3] Co-founder Community Forge[4]

On Thu, Dec 24, 2015, at 01:13 AM, Damian Lee wrote:

> D8 full time huh? Have you been contributing back to core then? I put
> a lot of time into D8! On 23 Dec 2015 13:57, "Matthew Slater"
> notifications@github.com wrote:
> 
> > Thanks for your answers I shall be experimenting with making my own
> > entityType! Could be valuable testing. Might be willing to submit
> > code suggestions. I'm good enough at git on drupal.org. been doing
> > d8 full time for 2 years now. Matthew
> > 
> > On Thu, Dec 24, 2015, at 12:21 AM, Amitai Burstein wrote:
> > 
> > > It _can_ be a node, the same way it could be any other
> > > ContentEntity.
> > > 
> > > Here's an answer I have in another thread:
> > > 1. OG7 is already not node-centric, every fieldable entity can be a
> > >    group/ group content
> > > 2. Adding an entity reference already in OG7 is what connects a
> > >    group content to a group
> > > 
> > > Groups are more often then not real content. They need to be
> > > published/ unpublished, comments, shown along other content, etc'
> > > 1. Groups can be private (with OG access module), so {node_access}
> > >    gives us all that
> > > 2. On top of that I think that migrating all the OG7 nodes to a new
> > >    entity wouldn't be nice for the site builders/ devs that already
> > >    use it.
> > > 
> > > — Reply to this email directly or view it on GitHub[1].
> > 
> > Links:
> > 1. https://github.com/amitaibu/og/issues/108#issuecomment-166892233
> > 
> > — Reply to this email directly or view it on GitHub
> > https://github.com/amitaibu/og/issues/108#issuecomment-166900954.
> 
> — Reply to this email directly or view it on GitHub[5].

Links:
1. http://matslats.net
2. http://matslats.net/complementary_currencies
3. http://shareable.net/users/matthew-slater
4. http://communityforge.net
5. https://github.com/amitaibu/og/issues/108#issuecomment-166903464
