### ISSUE TITLE
Can't edit my own user

### ISSUE THREAD

**Issue by matslats** [amitaibu/og#110]
I think I found a bug in \Drupal\og\OgAccess::userAccessEntity line 194
if ($user_access->isAllowed()) 
the it returns otherwise it is denied.
But if the result is neutral, then it is treated as denied.
So I don't know about caching, but if I had write access I would push this
if (!$user_access->isForbidden()) {
with a note for someone to check whether the neutral case should be cached the same as allowed or fobidden..

**Comment by amitaibu** [comment]
Does this still happen? If so, please re-open
