### ISSUE TITLE
Special casing OgMembership only to users

### ISSUE THREAD

**Issue by amitaibu** [amitaibu/og#116]
## Background

Currently we are treating all entities the same:
1. A user is connected to a group the same way a node is. 
2. All field storage is in fact an OgMembership entity
3. OgMembership is a ContentEntity that has stuff like state (active, pending, blocked)

The reason for doing this, is clear to me, in the sense that we didn't have to special case anything, and have any assumptions. 

I think that D8 gives us a good chance to add a bit more assumptions, in order to better model reality into the OG. The "reality" is that OgMembership makes sense only for users. I haven't seen cases where the membership had to hold more metadata when relating between nodes (I have had a few ideas of when it could be used, but I never saw them in real life - or ones that couldn't be done without it).
## Proposal

OgMembership should act as the field storage for User entity, and other entities should use the original field storage.

So the `OgAudience` field, and selection handler still applies to all entities - it's only how we save the data that changes.

This might have a positive impact on DX as `OgMembership`'s role becomes more clear; For example we could then reference OG roles from the OgMembership itself.

It will how ever add slightly more complexity, as we'd have to cater for this changes in several API function (e.g. `\Drupal\og\Og::getEntityGroups` might need to wrap something like `\Drupal\og\Og::getUserGroups`)

@RoySegall @damiankloip thoughts? objections?

**Comment by RoySegall** [comment]
So what I did for now is:
- [Removing the custom storage](https://github.com/amitaibu/og/pull/125/files#diff-3fc27bf69b47e26e4c1cbc57d8f7d2b4L33) which will give us normal ER fields. We need to prevent from the ER field to be created for users(`custom_storage => FALSE` for entity type user won't help, there is a fatal error)
- [Prevent from the field to be populated](https://github.com/amitaibu/og/pull/125/files#diff-0048dc77c304dea8a4ffee7b3bfddd79R67) when the destination entity type is a user(though when we manage to create custom storage for users we can remove that part) and maintain the membership records.

For now this is in a the lego phase - nothing is working and we need to construct but I think this is a good direction.

Thoughts?

**Comment by damiankloip** [comment]
The idea sounds workable I think. It makes sense to split the user and
content memberships if users require more things, like statuses. However,
if you wanted to get all content for the groups a user was in, for example,
this could be really painful?

Potentially OgUserMembership and OgContentMembership or something could
work?

I don't really understand that PR, sorry. It doesn't seem to do anything
that will help here. If we were going in this direction would the Og
audience field remain the same but only be used for users? Trying to revert
_everything_ it does seems really backwards. The problems you listed seems like the same problems we had that we solved a few months ago...

**Comment by amitaibu** [comment]
> if you wanted to get all content for the groups a user was in, for example,
> this could be really painful?

I agree there are cases where it would require more work. On the other hand, for example, when you delete multiple group content, we won't have to delete their related OgMembership. In the end I think `OgMembership` will become what you would _expect_ it to be.

> I don't really understand that PR
> 
> Potentially OgUserMembership and OgContentMembership or something could
> work?

I thought about it, but this it would be just easier to keep the audience field a "regular" ER field. 

My idea is:
- Keep our [fieldType](https://github.com/amitaibu/og/tree/e2a9bd4e746446331ee9a175dbcda64d2e990ca5/src/Plugin/Field/FieldType) so for example `Og::getAllGroupAudienceFields` keeps working the same. 
- Switch the field storage based on the Entity the field is attached to.

> I don't really understand that PR

Yes, I agree it's in a `WIP-not-even-alpha-move-along-don't-look-yet state` ;). I've changed it's title to reflect it.

**Comment by damiankloip** [comment]
Ha. Ok :)

So based on that. I think what's I mentioned previously might be the way to
go. We have two field types. The current one becomes the user specific one.
Otherwise we will be in a world of pain trying to case for custom storage
depending on the entity the field is attached to. I can't see that working
very well at all.

**Comment by amitaibu** [comment]
> We have two field types. 

Yes, that's indeed a possible way. @RoySegall was experimenting with the idea of keeping it as a single field type.

If we go with two fields, we'll still have to be sure that each one can be attached to the correct entity (i.e. one to `User` only, and the other to all but `User`).

> Otherwise we will be in a world of pain trying to case for custom storage
> depending on the entity the field is attached to

Can you expand a bit more where you see the pains?

**Comment by damiankloip** [comment]
Well, the code at the moment is assuming custom storage, which it should.
That's what it was designed for. If you try to re use the same field type,
nothing is gained apart from making sure it behaves one way for users and
another way for everything else. That sounds a lot like two field types to
me :) _especially_ as one will not even be dealing with og membership
entities. You would need to check the entity type anyway.

Another downside of the initial approach is that in one case you deal with
membership entities and another you just deal with the reference directly.
That's why I would see my idea of two reference entities working better.
Not sure tbh ...

**Comment by amitaibu** [comment]
To recap a conversation we had, we will go with two field types:
1. One for user - with OgMembership as storage
2. One for non-user - which just extends ER fields (and possibly adds constraints) with the default ER field storage

**Comment by RoySegall** [comment]
When [creating](https://github.com/amitaibu/og/blob/32056ad459c6803214c35d3d0d28c03e9b85bcac/src/Plugin/OgFields/AudienceField.php#L41-L41) the audience field the type will be different for each base entity type. Something like: 

``` php
[
  'type' => $this->getEntityType() == 'user' ? 'og_membership_reference' : 'og_standard_reference'
]
```

Right?

**Comment by damiankloip** [comment]
I would say maybe we should have two audience field plugins too? one which applies to each type? Then if the user field is added to something it is not meant to, we can just throw an exception rather than just falling back to the other field type?

**Comment by amitaibu** [comment]
I believe Roy's approach is fine in the sense that implementors can just `createField(AUDIENCE_FIELD...` without needing to care which entity it is -- it will attach the correct field type

> rather than just falling back to the other field type?

no falling back. But I do agree that if you will try to attach the wrong field type (i.e with Field's own API, instead of OG) an exception should be thrown

**Comment by pfrenssen** [comment]
I really like the idea of using field storage for the regular use cases, but I think we are making a mistake in hardcoding the custom storage to the User entity. This just goes against the flexibility that is expected of Drupal.

Wouldn't it be better to restore the `member_entity_type` and `member_entity_id` columns, turn the original OgMembership into a base class and have a OgUserMembership extend this with the convenience method `setUser()`?

Now it is not possible any more for people to provide custom storage for their own entities without having to copy the entire OgMembership class and adding in those columns themselves.

> I haven't seen cases where the membership had to hold more metadata when relating between nodes (I have had a few ideas of when it could be used, but I never saw them in real life - or ones that couldn't be done without it).

I have one in my current project. We will have a Subscriber entity that are basically people leaving their e-mail address to be notified of changes to certain groups without having a full account on the site (i.e. it should work without requiring a password). We need to add some metadata per group, basically what kind of notifications are being sent per group.

**Comment by amitaibu** [comment]
I'd like to "defend" the reason for special casing `User` - by the circular logic that it's special :) 

I mean, it represents a real human, that is a member of a group. That member has states (active, pending, blocked) and according to its roles has access to certain actions.

> We will have a Subscriber entity that are basically people leaving their e-mail address to be notified of changes to certain groups without having a full account

Yap, I've also encountered this use case sometimes in the past. The way I see it, there are several options:
1. Make it a real user, with a role indicating it's not a full blown user. Since, well, it's a user.
2. If option (1) is good enough (e.g. because one user might have multiple emails, or some edge case), then for me the `Subscriber` entity can hold the metadata. But the important properties like state, or role reference have no real meaning, since It's not really a _membership_ -- it's just a _subscription_.

With the above said, I do see your point, but I think that the fact we're able to simplify and say - `OgMembership` is only for `User`, will result with simpler code and simpler understanding of the code base.

**Comment by pfrenssen** [comment]
I'm fine with this obviously. I simply don't like hardcoding anything now that we are full blown OOP. The field storage is a great solution that will meet the vast majority of use cases.

For any bizarre outside-the-box requirements that require custom storage (like ours) it will be easy enough to copy the code from OgMembership into a custom class and adapt it to whatever is needed.
