### ISSUE TITLE
Fatal errors when trying to create a group

### ISSUE THREAD

**Issue by RoySegall** [amitaibu/og#124]
When I set up a group, just a group without any audeince field or group content defined, I'm getting this error:

> The website encountered an unexpected error. Please try again later.
> Drupal\Core\Entity\EntityStorageException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'member_entity_type' in 'field list': INSERT INTO {og_membership} (type, uuid, member_entity_type, member_entity_id, group_entity_type, group_entity_id, state, created, field_name, language) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9); Array ( [:db_insert_placeholder_0] => og_membership_type_default [:db_insert_placeholder_1] => c1d237c2-4c62-44ba-b202-2b4ae98ff3e5 [:db_insert_placeholder_2] => user [:db_insert_placeholder_3] => 1 [:db_insert_placeholder_4] => node [:db_insert_placeholder_5] => 3 [:db_insert_placeholder_6] => 1 [:db_insert_placeholder_7] => 1451813482 [:db_insert_placeholder_8] => og_group_ref [:db_insert_placeholder_9] => en ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 757 of core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
> Drupal\Core\Database\Statement->execute(Array, Array)
> Drupal\Core\Database\Connection->query('INSERT INTO {og_membership} (type, uuid, member_entity_type, member_entity_id, group_entity_type, group_entity_id, state, created, field_name, language) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9)', Array, Array)
> Drupal\Core\Database\Driver\mysql\Connection->query('INSERT INTO {og_membership} (type, uuid, member_entity_type, member_entity_id, group_entity_type, group_entity_id, state, created, field_name, language) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9)', Array, Array)
> Drupal\Core\Database\Driver\mysql\Insert->execute()
> Drupal\Core\Entity\Sql\SqlContentEntityStorage->doSaveFieldItems(Object)
> Drupal\Core\Entity\ContentEntityStorageBase->doSave(NULL, Object)
> Drupal\Core\Entity\EntityStorageBase->save(Object)
> Drupal\Core\Entity\Sql\SqlContentEntityStorage->save(Object)
> Drupal\Core\Entity\Entity->save()
> og_entity_insert(Object)
> call_user_func_array('og_entity_insert', Array)
> Drupal\Core\Extension\ModuleHandler->invokeAll('entity_insert', Array)
> Drupal\Core\Entity\EntityStorageBase->invokeHook('insert', Object)
> Drupal\Core\Entity\ContentEntityStorageBase->invokeHook('insert', Object)
> Drupal\Core\Entity\EntityStorageBase->doPostSave(Object, )
> Drupal\Core\Entity\ContentEntityStorageBase->doPostSave(Object, )
> Drupal\Core\Entity\EntityStorageBase->save(Object)
> Drupal\Core\Entity\Sql\SqlContentEntityStorage->save(Object)
> Drupal\Core\Entity\Entity->save()
> Drupal\node\NodeForm->save(Array, Object)
> call_user_func_array(Array, Array)
> Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object)
> Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object)
> Drupal\Core\Form\FormBuilder->processForm('node_group_form', Array, Object)
> Drupal\Core\Form\FormBuilder->buildForm(Object, Object)
> Drupal\Core\Entity\EntityFormBuilder->getForm(Object)
> Drupal\node\Controller\NodeController->add(Object)
> call_user_func_array(Array, Array)
> Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber{closure}()
> Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object)
> Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
> Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber{closure}()
> call_user_func_array(Object, Array)
> Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1)
> Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1)
> Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1)
> Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1)
> Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1)
> Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1)
> Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1)
> Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1)
> Stack\StackedHttpKernel->handle(Object, 1, 1)
> Drupal\Core\DrupalKernel->handle(Object)

For now I comment out `og_entity_insert` logic.

**Comment by pfrenssen** [comment]
How did you set up this group? Through the UI, or programmatically? I cannot replicate this.

**Comment by RoySegall** [comment]
UI. Maybe one of the PR fixed it.
