### ISSUE TITLE
Fatal error "undefined method IntegerData::isEmpty()" when saving group content

### ISSUE THREAD

**Issue by pfrenssen** [amitaibu/og#154]
A fatal error occurs when group content is saved that references a group:

```
Error: Call to undefined method Drupal\Core\TypedData\Plugin\DataType\IntegerData::isEmpty() in Drupal\Core\Entity\Plugin\Validation\Constraint\ValidReferenceConstraintValidator->validate() (line 78 of core/lib/Drupal/Core/Entity/Plugin/Validation/Constraint/ValidReferenceConstraintValidator.php).
```

This is caused by the original validator from the entity reference module being used in `OgStandardReferenceItem`. This is not compatible with the data format of our complex widget.

**Comment by pfrenssen** [comment]
This was discovered by running the test that is proposed in https://github.com/amitaibu/og/pull/149. This commit fixes the issue: https://github.com/amitaibu/og/commit/8e5b9797549e01a08aaa23ea555bd3b10c8e19e9

**Comment by amitaibu** [comment]
Can we close this?

**Comment by pfrenssen** [comment]
Oh yeah sure this is probably long fixed.
