### ISSUE TITLE
"Unfork" from Gizra/og

### ISSUE THREAD

**Issue by pfrenssen** [amitaibu/og#168]
This was originally forked off from Gizra/og but has since become the main repository. It would be nice if this was "unforked" so we don't always have to dance around the Gizra repository when creating pull requests :)

According to http://stackoverflow.com/questions/29326767/unfork-a-github-fork-without-deleting this is not possible through the UI or API, but can be achieved by contacting the Github support team.

**Comment by amitaibu** [comment]
I can also move it back to Gizra/og - would that help?

(cc @damiankloip @chx)

**Comment by damiankloip** [comment]
tbh, I don't care either way. I don't have (or see) any problem using amitaibu/og. It is going to end up here anyway though, so might as well move back. Not sure what dance @pfrenssen is doing, but I just go straight to the current one..

Why do we need to unfork? Let's just merge, or push the 8.x branch directly to gizra/og? This was meant for early development, and that has been done now :)

**Comment by pfrenssen** [comment]
The problem with moving back is that all current open issues and PRs will stay behind. This is not such a huge deal since the issues and PRs we care about will migrate to Gizra eventually.

@damiankloip The dance I'm doing is this one :) https://www.youtube.com/watch?v=YsDwiwQGtlc

**Comment by RoySegall** [comment]
I think it's to early. We are in our container and if we go to back to gizra/OG we will have a lot of noise from 7.x-2.x issues.

We should, IMO, un-fork once a couple of core issues will done such as: selection handler and plug the entity access to OG access workflow.

**Comment by pfrenssen** [comment]
I didn't realize this was intended to be a temporary repo that is going to flow back to Gizra once it is in a somewhat usable state.

**Comment by japerry** [comment]
It would also be nice if we can get this code mirrored back into the drupal.org 8.x repo. As it stands, distributions relying on OG 8.x cannot be built on drupal.org

**Comment by amitaibu** [comment]
no problem, I'll push 8.x to d.o. as-well

**Comment by amitaibu** [comment]
@japerry which means you will owe OG a PR ;)

**Comment by chx** [comment]
Could we please not do that? Or indicate some big red scary letters it's not ready yet? I really would like to find the time (and I will!) to convert to a service from statics.

**Comment by amitaibu** [comment]
I was indeed thinking about some scary letters :)

I would also be ok, with waiting a bit more - until we have OG core a bit more solid. I finally got some work time allocated for OG, so I hope this will happen sooner than later..

**Comment by chx** [comment]
Brief chat on IRC PM ?
