### ISSUE TITLE
Clear up confusion about which field storage type is used for users

### ISSUE THREAD

**Issue by pfrenssen** [amitaibu/og#177]
We have two types of storage for the group audience field: one for user entities, and one for all other entities. This is decided in `AudienceField::getFieldStorageConfigBaseDefinition()`:

```
public function getFieldStorageConfigBaseDefinition(array $values = array()) {
  $values = [
    // ...
    'type' => $this->getEntityType() == 'user' ? 'og_membership_reference' : 'og_standard_reference',
  ];
  // ...
}
```

The above code looks good to me, when the entity type is a user, then the `og_membership_reference`  field type is used. For all other cases the `og_standard_reference` is used.

However when I look at the descriptions for these two field types, they seem to claim the opposite. The `og_membership_reference` says it is for a "non user based entity":

```
/**
 * Class OgMembershipReferenceItem.
 *
 * @FieldType(
 *   id = "og_membership_reference",
 *   description = @Translation("An entity field containing an OG membership reference for non user based entity."),
 * )
 */
class OgMembershipReferenceItem extends OgStandardReferenceItem {}
```

While the `og_standard_reference` field type says that it is for a "user based entity":

```
/**
 * Class OgStandardReferenceItem.
 *
 * @FieldType(
 *   id = "og_standard_reference",
 *   description = @Translation("An entity field containing an OG membership reference for user based entity."),
 * )
 */
class OgStandardReferenceItem extends OgStandardReferenceItem {}
```

@RoySegall can you have a look? Which is correct?

**Comment by damiankloip** [comment]
Yes, just seems like a mix up. The descriptions just need to be switched I think.

**Comment by amitaibu** [comment]
`og_standard_reference` isn't very clear. 

maybe `og_membership_non_user_reference` and `og_membership_user_reference` would be better?

**Comment by amitaibu** [comment]
Closing in favor of #212
