### ISSUE TITLE
What is a user based entity?

### ISSUE THREAD

**Issue by chx** [amitaibu/og#220]
`OgStandardReferenceItem` has 

> An entity field containing an OG membership reference for user based entity

What on earth is that? I know what's a user entity but what is a user _based_ entity?

**Comment by amitaibu** [comment]
Seems like a wrong definition. I'll create a PR to fix it

**Comment by dakala** [comment]
@amitaibu Sorry didn't notice you've assigned this to yourself. The PR's open so you can always review anyway. It's a small fix.

**Comment by amitaibu** [comment]
Great, thanks for tackling it.
