### ISSUE TITLE
Create a RoleManager service

### ISSUE THREAD

**Issue by pfrenssen** [amitaibu/og#221]
Currently the `GroupManager` service is taking up too many responsibilities and has become a little overweight as a result.

We should refactor the methods related to managing roles into a separate `RoleManager` service:
- `createRoles()`
- `getDefaultRoles()`
- `removeRoles()`

**Comment by pfrenssen** [comment]
@amitaibu, do you think it would be a good idea to create a new "Novice" label and attach it to this issue? If we can identify some low hanging fruit as easy fixes this might help to lure new contributors.

**Comment by amitaibu** [comment]
Novice label added!

**Comment by pfrenssen** [comment]
This is currently blocked by https://github.com/amitaibu/og/pull/192 but that is near completion.

**Comment by amitaibu** [comment]
This is in https://github.com/Gizra/og/blob/02cb66ce93ed710c62dfa87110e41f8c5af0d723/src/OgRoleManager.php
