### ISSUE TITLE
Provide an interface for PermissionManager

### ISSUE THREAD

**Issue by pfrenssen** [amitaibu/og#228]
Currently `PermissionManager` doesn't have an interface. Since this is a service that can be injected into other code (for example in `OgAccess`) it should have an interface so it can be swapped out with another implementation.

**Comment by dakala** [comment]
@pfrenssen @amitaibu We've already got PermissionManagerInterface and og.permission_manager service. This should be closed too.

**Comment by amitaibu** [comment]
Thanks. Next time feel free to close.
