### ISSUE TITLE
Handle special issue 'update group'

### ISSUE THREAD

**Issue by idimopoulos** [amitaibu/og#246]
Currently I can see that the permission handling is being built in the upcoming PRs but there is still one thing missing.
While in OgAccess there is a special handling of the 'administer group' permission, there is no special handling for the 'update group' permission.
I added a small two lines fix to workaround this issue which can be found in
https://github.com/ec-europa/og/commit/00978da35e906077c47fe57adbea362a1cbbfc8f
(sorry if it is inappropriate to link other forks' commits). I haven't created any test because I do not know if this is a good way to go or if there is forseen a different way of handling all the special permissions.

The fork and branch I worked based on the https://github.com/amitaibu/og/tree/check-group-content-crud-access

**Comment by amitaibu** [comment]
Indeed, we discussed it in#240 with @pfrenssen but I think it didn't went in in the end. Care to work on a PR?

**Comment by idimopoulos** [comment]
Yes but since it's your module, I would like to know if you want to have it as a simple check or if your are planning for a generic special permission handler. Right now you only have 2 special permissions ('administer group' and 'update group'). If the module will only have 2 special permissions, it can be handled with two simple checks, the way the 'administer group' permission is being handled now.

**Comment by amitaibu** [comment]
Yes, I think we can start with the simple checks to begin with.

**Comment by idimopoulos** [comment]
@amitaibu sorry if this is too terrible, I'm open for reviews.
PR: https://github.com/amitaibu/og/pull/250
