### ISSUE TITLE
Can't save an existing OgRole

### ISSUE THREAD

**Issue by Nyliandis** [amitaibu/og#247]
Hi,
I try to update an existing OgRole but when i save the entity this error is throw :

Error: Class 'Drupal\og\Exception\OgRoleException' not found in /modules/contrib/og/src/Entity/OgRole.php on line 258, referer: admin/config/group/roles/node/structure/manage/node-bundle-member

After ivestigate, i think the save() method try to change the id, although i change it or no.

Have a good day.

**Comment by amitaibu** [comment]
@Nyliandis thanks. Can you provide steps to reproduce. or even better - a PR to fix it? :)

**Comment by amitaibu** [comment]
Should be fixed here -- https://github.com/amitaibu/og/pull/217#discussion_r70782037
