### ISSUE TITLE
Prevent duplicate OgMembership

### ISSUE THREAD

**Issue by amitaibu** [amitaibu/og#259]
\Drupal\og\Entity\OgMembership::preSave should throw an exception in case the same membership is re-created.

**Comment by amitaibu** [comment]
@dakala maybe you'd want to pick this one as your next issue 😄

**Comment by dakala** [comment]
That's ok. You may assign it me 😄

**Comment by dakala** [comment]
@amitaibu This is another one that's should be closed too.
