### ISSUE TITLE
Code sniffer should run in own Travis env

### ISSUE THREAD

**Issue by amitaibu** [amitaibu/og#262]
Follow up for #251. Coder shouldn't run on all env - we should have a nicer matrix for that

This can be used as reference -- https://github.com/Gizra/generator-hedley/pull/110/files

/cc @ordavidil

**Comment by pfrenssen** [comment]
Good idea, we should only run it on PHP7 with the latest version of D8. It would also be nice to reorder the matrix to run the PHP7 tests first. Then we get our first test result back quicker.
