### ISSUE TITLE
Prevent OgMemberships to be created with the 'non-member' and 'member' role

### ISSUE THREAD

**Issue by pfrenssen** [amitaibu/og#293]
Currently it is possible to create OgMembership entities in which the user has the 'non-member' role.

We should throw an exception when someone tries to sneak in the `OgRoleInterface::ANONYMOUS` role.

This was suggested by @amitaibu in https://github.com/amitaibu/og/pull/217#discussion_r73567630 but has been split off to a separate ticket.

**Comment by amitaibu** [comment]
I've updated title to also include the member role. Like in Drupal core, a user isn't saved with the authenticated role -- it's implied by it being a user.

**Comment by dakala** [comment]
@amitaibu Is this ticket still valid?

**Comment by amitaibu** [comment]
Yeah, you can keep open until your PR will get in.

**Comment by dakala** [comment]
https://github.com/Gizra/og/pull/174
