### ISSUE TITLE
Create a dedicated RoleManager service

### ISSUE THREAD

**Issue by pfrenssen** [amitaibu/og#295]
We currently have a number of methods in `GroupManager` which are not actually dealing with groups; they deal with OG roles:
- `::createPerBundleRoles()`
- `::getDefaultRoles()`
- `::getRequiredDefaultRoles()`
- `::removeRoles()`
## Scope
1. Create the `OgRoleManager` service and move the 4 methods in there.
2. Create the `OgRoleManagerInterface` which documents the public methods in the service.
3. Tests should obviously pass :)

**Comment by pfrenssen** [comment]
@amitaibu do you agree this would be an improvement? Should it be called `RoleManager` or `OgRoleManager`?

**Comment by amitaibu** [comment]
Sounds great. I think `OgRoleManager` would be better.

**Comment by pfrenssen** [comment]
Great! I'll update the issue summary.

**Comment by dakala** [comment]
Hi @pfrenssen

I'd like to help with this issue please

**Comment by dakala** [comment]
Refactor done. Tests not passing yet

**Comment by pfrenssen** [comment]
@dakala thanks for picking this up! Looking forward to the PR! :)

**Comment by amitaibu** [comment]
Feel free to open PR even before it's complete - you might earn some early review :)
