### ISSUE TITLE
Remove OgSelection::setAccount/getAccount

### ISSUE THREAD

**Issue by amitaibu** [amitaibu/og#31]
We should change the selection handler's `currentUser` instead.

@damiankloip care to give it a try?

**Comment by damiankloip** [comment]
@amitaibu sure, I will take a look. The current methods actually just overwrite what's there. It means in the tests we will likely need a bit more work. I'll see how things look.

**Comment by damiankloip** [comment]
I think we did this: https://github.com/amitaibu/og/pull/33
