### ISSUE TITLE
Please update 8.x-1.x branch from Gizra/og

### ISSUE THREAD

**Issue by damienmckenna** [amitaibu/og#319]
Could you please update the 8.x-1.x branch from upstream, it's proving hard to use diffs from this repo's PRs because of the disconnect. Thank you.

**Comment by amitaibu** [comment]
Thanks @damienmckenna for working on this. I've granted you commit access to the `amitaibu/og` repo :)

**Comment by damienmckenna** [comment]
Thanks!

**Comment by damienmckenna** [comment]
This has been handled by PR #320.
