### ISSUE TITLE
createField does not take into account OgFields type

### ISSUE THREAD

**Issue by mradcliffe** [amitaibu/og#39]
Should createField take into account the type from OgFields plugin, or should the type be removed from the plugin definition? In Drupal 7, type was an array, and it looks to be just a string in OgFields plugins.

I can hack on this, but probably after #20.

**Comment by damiankloip** [comment]
Not sure I fully get this. So E.g. `'type' => 'og_membership_reference'` in `AudienceField`, where is that not being used? These plugins return the full definition.

**Comment by amitaibu** [comment]
> Should createField take into account the type from OgFields plugin

Yes, currently the `\Drupal\og\Og::createField` is hardcoded to a field called `OG_AUDIENCE_FIELD`. This method should, like in D7, accept the name of the field as we used to define it in `hook_og_fields_info()` e.g. https://github.com/Gizra/og/blob/7.x-2.x/og.module#L1012

I was actually thinking of tackling this one, but go ahead and do it :)

**Comment by mradcliffe** [comment]
Sorry the Annotation type.

``` php
/**
 * @OgFields(
 *  id = "some_id",
 *  type = "group",
 *  description = @Translation("some description"),
 * )
 */
)
```

**Comment by amitaibu** [comment]
I went over #20 in more depth, and it's actually taking into account the field name.

@mradcliffe can you clarify what you mean then?

**Comment by amitaibu** [comment]
@mradcliffe fyi, I'm doing so refactoring to #20.

**Comment by damiankloip** [comment]
Is this now a non-issue due to #20 ? Or does it still need some discussion/action?

**Comment by amitaibu** [comment]
Should be fixed.
