### ISSUE TITLE
Fatal error when saving a group content node

### ISSUE THREAD

**Issue by pfrenssen** [amitaibu/og#62]
When I try to submit a group content node I get a fatal error. I'm using a clean 8.1.x install. It happens on both the `standard` and `minimal` install profiles. I'm following the instructions in the README to set up the group type and group audience field but I'm probably just missing a crucial step.

Steps to replicate:
1. Perform a clean install using the minimal or standard profile.
2. Enable OG.
3. Create a new content type named 'group'.
4. Using `drush php`:
   - `\Drupal\og\Og::groupManager()->addGroup('node', 'group');`
   - `\Drupal\og\Og::createField(\Drupal\og\OgGroupAudienceHelper::DEFAULT_FIELD, 'node', 'article');`
5. Submit the form at `/node/add/article`.

Result:

```
Recoverable fatal error: Argument 1 passed to Drupal\Core\Entity\EntityReferenceSelection\SelectionPluginManager::getSelectionHandler() must implement interface Drupal\Core\Field\FieldDefinitionInterface, null given, called in /home/pieter/v/drupal/drupal/modules/og/src/Plugin/EntityReferenceSelection/OgSelection.php on line 40 and defined in Drupal\Core\Entity\EntityReferenceSelection\SelectionPluginManager->getSelectionHandler() (line 99 of core/lib/Drupal/Core/Entity/EntityReferenceSelection/SelectionPluginManager.php).
Drupal\Core\Entity\EntityReferenceSelection\SelectionPluginManager->getSelectionHandler(NULL)
Drupal\og\Plugin\EntityReferenceSelection\OgSelection->getSelectionHandler()
Drupal\og\Plugin\EntityReferenceSelection\OgSelection->buildEntityQuery()
Drupal\Core\Entity\Plugin\EntityReferenceSelection\DefaultSelection->validateReferenceableEntities(Array)
Drupal\Core\Entity\Plugin\Validation\Constraint\ValidReferenceConstraintValidator->validate(Object, Object)
```

**Comment by chx** [comment]
I can reproduce this. I believe this has a lot to do with the field config vs field storage config in https://github.com/amitaibu/og/pull/80 .

**Comment by chx** [comment]
On more discussion, I have NFI why this happens :) but will investigate tomorrow.

**Comment by damiankloip** [comment]
See https://github.com/amitaibu/og/pull/81

**Comment by pfrenssen** [comment]
I can confirm that this is now fixed. Thanks!
