### ISSUE TITLE
Move og_ui in to modules subdirectory

### ISSUE THREAD

**Issue by RoySegall** [amitaibu/og#68]
I think a lot of modules keep their sub modules in a subdirectory called `modules`. I think we should go in the same direction for og_ui(for now) and for the upcoming modules.

**Comment by amitaibu** [comment]
:+1:

**Comment by damiankloip** [comment]
Totally agree, this is how it is in the 7.x branch too. Just wondering if it can wait until https://github.com/amitaibu/og/pull/40 is done? However, git is clever, so reading with the rename might be smooth...

**Comment by MPParsley** [comment]
@amitaibu, @pfrenssen could you close this issue?

In https://github.com/amitaibu/og/issues/315 it's decided to remove the og_ui module.
