### ISSUE TITLE
Re-enable checks in og_entity_create_access()

### ISSUE THREAD

**Issue by amitaibu** [amitaibu/og#70]
#51 follow up

Currently due to Drupal core limitations the entity data isn't passed to the hook.

**Comment by chx** [comment]
Sure but we do not need to do anything. The code already presumes that patch landed.

**Comment by amitaibu** [comment]
Sorry, I meant this part - https://github.com/amitaibu/og/blob/8.x-1.x/og.module#L174-L179

**Comment by chx** [comment]
So that piece is meaningless as it stands right now because it's an infinite loop. What, exactly, did we want to there?

**Comment by amitaibu** [comment]
Some code in #86
