### ISSUE TITLE
Allow altering OG permissions

### ISSUE THREAD

**Issue by amitaibu** [amitaibu/og#76]
https://github.com/amitaibu/og/pull/47#issuecomment-162075845

**Comment by amitaibu** [comment]
@damiankloip Is the lack of altering (`hook_permissions_alter`) in D8 core is:

a) It's there Amitai, you just missed it
b) It's a mistake
c) There a good reason which is ______

:smiley:

**Comment by damiankloip** [comment]
@amitaibu I'll take option b I guess. Looks like it just doesn't exist (but didn't in D7 either?!). Looks like people do want this thought, see https://www.drupal.org/node/763074

**Comment by amitaibu** [comment]
Thanks, so I'll go and add this alter - because there doesn't seem to be a good reason why it should not be added.

**Comment by dawehner** [comment]
In core an alter hook wouldn't really make sense, because on runtime there is no validation whether a permission is correct, so removing elements wouldn't be possible and let's be honest, does someone really care about the title/description of those?

**Comment by amitaibu** [comment]
>  because on runtime there is no validation whether a permission is correct,

It's a valid point.

OG ideology is to follow core and provide the same roles/ permissions mechanism on the groups level rather than on the site-wide level. So for consistency let's keep this approach, and also not provide the alter hook. 

We can revisit this later if needed.

**Comment by damiankloip** [comment]
This wouldn't need to be executed during runtime. Similar to altering
plugin definitions maybe?

I am totally fine with not adding this though!

**Comment by amitaibu** [comment]
Yeah, let's not add for now. It's simpler ;)

**Comment by damiankloip** [comment]
Yep. Can't argue with that. Something that doesn't exist is always easier
to maintain and test :)
